### ISSUE TITLE
[QUESTION] New doc or example

### ISSUE THREAD

**Issue by Radeonisos** [4D-Technologies/openidconnect_flutter#45]
Hello

I'm trying to set up login management with keycloak in the PKCE flow (without implicit flow) in flutter web but I'm having trouble setting it all up. Is it possible to have an example? or more detailed documentation ?
thank you for your work

**Comment by ahmednfwela** [comment]
@Radeonisos you can find an example here https://github.com/4D-Technologies/openidconnect_flutter/tree/main/openidconnect/example

**Comment by Radeonisos** [comment]
thanks i will work on it with your example

**Comment by Radeonisos** [comment]
i think i almost success it but after the the redirect (i can't use the login popup) on my callback.html, my app loop on the same page.
I think i need to " This will then be processed using the OpenIdConnect.processStartup or by the OpenIdConnectClient on .create()" 
But i don't know how to use it.

**Comment by Radeonisos** [comment]
i run on step by step and the crash come on this line : 
![image](https://github.com/4D-Technologies/openidconnect_flutter/assets/15607745/73484a0b-5864-4870-b9d3-7dd0eb5ed372)

in the 
![image](https://github.com/4D-Technologies/openidconnect_flutter/assets/15607745/858a6f9c-fba4-42d2-8ad1-511751d85837)

**Comment by ahmednfwela** [comment]
what error do you get?

**Comment by Radeonisos** [comment]
i found the error is due to my url tokenEndPoint. I create (for now) the configuration manually. But now i need to user " final configuration =
                        await OpenIdConnect.getConfiguration(discoveryUrl);" 
but i need to find the good discoveryUrl.
I will update this "issue"

**Comment by Radeonisos** [comment]
i success it 👍 

I analyze my router and the example and all works, i close it (If someone (with flutter web, pkce flow and no popup) have trouble i can help i think
